import type { ContentItem } from '@/types'

export const SAMPLE_CONTENT: ContentItem[] = [
  // ===== ART GALLERY — artbymarchese.com =====
  // --- ORIGINAL ART (Wall-displayed) ---
  {
    id: 'art-1',
    zoneId: 'art_gallery',
    title: "I'm In Love With Money",
    subtitle: 'Original — SOLD',
    description: 'The crown jewel of the Art by Marchese collection. A monumental original work exploring wealth, desire, and pop-culture iconography. Exhibited at Art Basel Miami. This piece has sold for $1,000,000.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/Im_In_Love_With_Money_Canvas_On_Easel.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD', gallery: 'Art Basel Miami' },
    price: 1000000,
  },
  {
    id: 'art-2',
    zoneId: 'art_gallery',
    title: 'Devil In The Details',
    subtitle: 'Original — $100,000',
    description: 'A striking original exploring the duality of ambition and temptation. Bold colors and intricate detailing define this signature Marchese piece.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/IMG-3914.png?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 100000,
    purchasable: true,
  },
  {
    id: 'art-3',
    zoneId: 'art_gallery',
    title: 'We Are Venom',
    subtitle: 'Original — $100,000',
    description: 'A powerful pop-culture original blending comic-book energy with fine art technique. The symbiote comes alive in Marchese\'s signature mixed-media style.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/B2325828-B1A4-4C6A-AA33-9848D15EEC4C.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 100000,
    purchasable: true,
  },
  {
    id: 'art-4',
    zoneId: 'art_gallery',
    title: 'Run It Up',
    subtitle: 'Original — $100,000',
    description: 'An original work channeling relentless ambition and hustle culture through Marchese\'s distinctive visual language.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/A813D1BB-1B77-4ACF-AE96-E1A578CF7E48.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 100000,
    purchasable: true,
  },
  {
    id: 'art-5',
    zoneId: 'art_gallery',
    title: 'Carat King',
    subtitle: 'Original — $100,000',
    description: 'A dazzling exploration of luxury and status, rendered in Marchese\'s bold pop-art style with meticulous detail.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/3CE0517C-32D4-49C9-B9E3-CAF65CC2105E.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 100000,
    purchasable: true,
  },
  {
    id: 'art-6',
    zoneId: 'art_gallery',
    title: "Blowin' Money",
    subtitle: 'Original — SOLD',
    description: 'A sold-out original capturing the extravagance and audacity of wealth in motion. Part of the permanent Marchese collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/9D807BBF-684B-4CB1-A25B-9D8EDE54CA07.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 88888.88,
  },
  {
    id: 'art-7',
    zoneId: 'art_gallery',
    title: 'Horsepower',
    subtitle: 'Original — SOLD',
    description: 'Where automotive culture meets fine art. A sold-out original from the Marchese collection celebrating raw power and craftsmanship.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/IMG_7777.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 75000,
  },
  {
    id: 'art-8',
    zoneId: 'art_gallery',
    title: 'Sitting on Top of the World',
    subtitle: 'Original — SOLD',
    description: 'A triumphant original depicting the pinnacle of success. Sold and part of a private collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/2106565E-DEFE-4BD9-AE5C-88B3D84DD33A.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 75000,
  },
  {
    id: 'art-9',
    zoneId: 'art_gallery',
    title: 'Bank of Daffy',
    subtitle: 'Original — SOLD',
    description: 'Pop-culture meets finance in this iconic Marchese original. Sold and part of a private collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/67816523995__671E86F7-E39F-4F88-8DA1-AF2EA918CC14_1.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 60000,
  },
  {
    id: 'art-10',
    zoneId: 'art_gallery',
    title: 'La Belleza De La Muerte',
    subtitle: 'Original — $55,000',
    description: 'A hauntingly beautiful original exploring themes of beauty and mortality through vibrant color and cultural symbolism.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/La_Belleza_De_La_Muerte.heic?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 55000,
    purchasable: true,
  },
  // --- MORE ORIGINALS (browsable via overlay) ---
  {
    id: 'art-11',
    zoneId: 'art_gallery',
    title: 'Cat Woman',
    subtitle: 'Original — $50,000',
    description: 'A fierce pop-culture portrait reimagining the iconic character through Marchese\'s lens of luxury and power.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/CE9AFBD0-6E01-4B81-AF49-EC23ACB042A2.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 50000,
    purchasable: true,
  },
  {
    id: 'art-12',
    zoneId: 'art_gallery',
    title: 'Leave Me Vlone',
    subtitle: 'Original — SOLD',
    description: 'A streetwear-meets-fine-art original. Sold and part of a private collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/1A0D5E4A-CD35-45B9-855B-9D410AB7A094_2.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 50000,
  },
  {
    id: 'art-13',
    zoneId: 'art_gallery',
    title: 'Designer Drip',
    subtitle: 'Original — $33,000',
    description: 'A 3D mixed-media exploration of designer culture and artistic expression.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/37DA7B0D-C36F-404F-8DE3-E17E6593343D.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 33000,
    purchasable: true,
  },
  {
    id: 'art-14',
    zoneId: 'art_gallery',
    title: 'Hearts of Stone',
    subtitle: 'Original — $30,000',
    description: 'Marble Chrome Hearts logo rendered as fine art — where streetwear iconography meets sculptural permanence.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/Marble_Chrome_Hearts_Logo.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 30000,
    purchasable: true,
  },
  {
    id: 'art-15',
    zoneId: 'art_gallery',
    title: 'Beached',
    subtitle: 'Original — SOLD',
    description: 'A coastal original blending luxury lifestyle imagery with Marchese\'s signature pop-art aesthetic.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/520D1B43-C60E-433F-9072-75DDF89484B7.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 30000,
  },
  {
    id: 'art-16',
    zoneId: 'art_gallery',
    title: 'Forever Love',
    subtitle: 'Original — SOLD',
    description: 'Mickey & Minnie reimagined through Marchese\'s luxury pop-art vision. Sold and cherished in a private collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/IMG_6410.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 25000,
  },
  {
    id: 'art-17',
    zoneId: 'art_gallery',
    title: 'The Batman',
    subtitle: 'Original — $25,000',
    description: 'The Dark Knight rendered in Marchese\'s bold, textured style — comic-book heroism elevated to gallery-wall status.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/04A0D404-4F6A-4D48-8130-453870C8CEC1.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 25000,
    purchasable: true,
  },
  {
    id: 'art-18',
    zoneId: 'art_gallery',
    title: 'Twin Flames',
    subtitle: 'Original — $22,222.22',
    description: 'A passionate exploration of connection and duality, rendered with Marchese\'s distinctive energy and color palette.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/A3EEB0EE-635C-4BE4-B61A-7FF2C5DEE111.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 22222.22,
    purchasable: true,
  },
  {
    id: 'art-19',
    zoneId: 'art_gallery',
    title: 'Scrooge Hermes',
    subtitle: 'Original — SOLD',
    description: 'Scrooge McDuck meets Hermès in this iconic crossover. Sold and part of a private collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/Scrooge_Hermes.png?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 22500,
  },
  {
    id: 'art-20',
    zoneId: 'art_gallery',
    title: 'Kaws Dunk',
    subtitle: 'Original — $23,000',
    description: 'Cartoon character in a Lakers jersey holding a Supreme basketball against a starry background. Streetwear culture immortalized on canvas.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/KawsDunkonCanvas.png?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 23000,
    purchasable: true,
  },
  {
    id: 'art-21',
    zoneId: 'art_gallery',
    title: 'Just Dripping',
    subtitle: 'Original — $20,000',
    description: 'A 3D Nike-inspired mixed-media piece dripping with Marchese\'s signature style and energy.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/image0_11.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 20000,
    purchasable: true,
  },
  {
    id: 'art-22',
    zoneId: 'art_gallery',
    title: 'Mind Games',
    subtitle: 'Original — SOLD',
    description: 'A cerebral original exploring perception and reality. Sold and part of a private collection.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/image.heic?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 18500,
  },
  {
    id: 'art-23',
    zoneId: 'art_gallery',
    title: 'Anime is Gucci',
    subtitle: 'Original — $18,000',
    description: 'Where Japanese anime aesthetics meet Italian luxury fashion — a Murakami-inspired Marchese original.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/IMG-3113.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'Available' },
    price: 18000,
    purchasable: true,
  },
  {
    id: 'art-24',
    zoneId: 'art_gallery',
    title: 'Arcade',
    subtitle: 'Original — SOLD',
    description: 'A nostalgic original blending retro gaming culture with contemporary fine art. Sold.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/FullSizeRender.heic?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Original Art', status: 'SOLD' },
    price: 75000,
  },
  // --- PRINTS ---
  {
    id: 'art-25',
    zoneId: 'art_gallery',
    title: 'Smoke Break',
    subtitle: 'Print — $1,400',
    description: 'A stylish print from the Art by Marchese collection. High-quality reproduction on premium canvas.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/image0_9.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1400,
    purchasable: true,
  },
  {
    id: 'art-26',
    zoneId: 'art_gallery',
    title: 'Rolex Flex',
    subtitle: 'Print — $1,800',
    description: 'Luxury timepiece meets pop art in this striking canvas print.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/Rolexflex_blue_inlivingspace.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-27',
    zoneId: 'art_gallery',
    title: 'Roadrunner Strikes Back',
    subtitle: 'Print — $1,400',
    description: 'The classic cartoon character reimagined with Marchese\'s luxury pop-art sensibility.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/RoadrunnerStrikesBackinlivingroom.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1400,
    purchasable: true,
  },
  {
    id: 'art-28',
    zoneId: 'art_gallery',
    title: 'Rari Drip',
    subtitle: 'Print — $1,400',
    description: 'Ferrari luxury meets artistic expression in this vibrant canvas print.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/IMG-2593.png?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1400,
    purchasable: true,
  },
  {
    id: 'art-29',
    zoneId: 'art_gallery',
    title: 'Paper Chaser',
    subtitle: 'Print — $1,200',
    description: 'Bugs Bunny meets Hermès in this playful yet luxurious canvas print.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/BugsHermesOnCanvas.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1200,
    purchasable: true,
  },
  {
    id: 'art-30',
    zoneId: 'art_gallery',
    title: 'New Tweet',
    subtitle: 'Print — $1,200',
    description: 'Social media culture immortalized as pop art. A commentary on digital communication.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/IMG_1333.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1200,
    purchasable: true,
  },
  {
    id: 'art-31',
    zoneId: 'art_gallery',
    title: 'Mask On',
    subtitle: 'Print — $1,200',
    description: 'Identity and persona explored through Marchese\'s signature pop-culture lens.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/MaskOnInLivingSpace.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1200,
    purchasable: true,
  },
  {
    id: 'art-32',
    zoneId: 'art_gallery',
    title: 'Martian Madness',
    subtitle: 'Print — $1,200',
    description: 'An out-of-this-world print blending sci-fi energy with luxury pop-art aesthetics.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/IMG_1269.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1200,
    purchasable: true,
  },
  {
    id: 'art-33',
    zoneId: 'art_gallery',
    title: 'Lambo Scrooge',
    subtitle: 'Print — $1,800',
    description: 'Scrooge McDuck behind the wheel of a Lamborghini — wealth culture at its most playful.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/LamboScroogeinlivingspace.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-34',
    zoneId: 'art_gallery',
    title: 'I Am Ironman',
    subtitle: 'Print — $1,800',
    description: 'Tony Stark\'s alter ego reimagined through the Marchese pop-luxury aesthetic.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/image1_1.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-35',
    zoneId: 'art_gallery',
    title: 'Here Comes Trouble',
    subtitle: 'Print — $1,200',
    description: 'Mischief and mayhem rendered in vibrant color and bold composition.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/IMG_1399.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1200,
    purchasable: true,
  },
  {
    id: 'art-36',
    zoneId: 'art_gallery',
    title: "Don't Blow It",
    subtitle: 'Print — $1,800',
    description: 'David reimagined with bubblegum — classical sculpture meets contemporary irreverence.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/davidgummarbleinlivingroom.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-37',
    zoneId: 'art_gallery',
    title: 'Dollaz On My Head',
    subtitle: 'Print — $1,400',
    description: 'Money on the mind — a bold statement piece about ambition and focus.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/MoneyOnMindMyInLivingSpace.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1400,
    purchasable: true,
  },
  {
    id: 'art-38',
    zoneId: 'art_gallery',
    title: "Breakfast At Tiffany's",
    subtitle: 'Print — $1,800',
    description: 'Audrey Hepburn\'s iconic role reimagined through Marchese\'s luxury pop-art lens.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/HepburnInLivingSpace.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-39',
    zoneId: 'art_gallery',
    title: 'Blow Me',
    subtitle: 'Print — $1,800',
    description: 'Marilyn Monroe with bubblegum — Hollywood glamour meets pop-art playfulness.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/Marilynguminlivingroom.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-40',
    zoneId: 'art_gallery',
    title: 'Bitcoin Mining',
    subtitle: 'Print — $1,800',
    description: 'Crypto culture meets fine art — digital wealth rendered in physical medium.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/image_719dea20-a47e-494d-afa9-bc6ee10d6cb4.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  {
    id: 'art-41',
    zoneId: 'art_gallery',
    title: 'Baby Come Back',
    subtitle: 'Print — $1,800',
    description: 'Nostalgia and pop-culture energy captured in a vibrant living-space-ready print.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/products/BabyComeBack-LivingRoomcopy.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Prints', status: 'Available' },
    price: 1800,
    purchasable: true,
  },
  // --- WEARABLE ART ---
  {
    id: 'art-42',
    zoneId: 'art_gallery',
    title: 'The Drip Mini Dress',
    subtitle: 'Wearable Art — $800',
    description: 'A 1-of-1 wearable art mini dress by Chris Marchese. Hand-painted and designed for the intersection of fashion and fine art.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/Drip_Mini_Dress_Miami_4.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Wearable Art', status: 'Available' },
    price: 800,
    purchasable: true,
  },
  {
    id: 'art-43',
    zoneId: 'art_gallery',
    title: 'The Drip Dress',
    subtitle: 'Wearable Art — $800',
    description: 'Hand-painted wearable art dress — each piece is a unique original by Chris Marchese.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/2.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Wearable Art', status: 'Available' },
    price: 800,
    purchasable: true,
  },
  {
    id: 'art-44',
    zoneId: 'art_gallery',
    title: 'The Drip Tee',
    subtitle: 'Wearable Art — $600',
    description: '1-of-1 wearable art t-shirt by Chris Marchese, hand-painted with black acrylic and rhinestones.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/DripLine.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Wearable Art', status: 'Available' },
    price: 600,
    purchasable: true,
  },
  {
    id: 'art-45',
    zoneId: 'art_gallery',
    title: 'The Drip Crop Top',
    subtitle: 'Wearable Art — $180',
    description: 'Wearable art crop top from the Drip collection. Hand-finished by Chris Marchese.',
    mediaType: 'image',
    mediaUrl: 'https://artbymarchese.com/cdn/shop/files/10F19923-71AB-4646-9009-889C8C62A14B.jpg?v=1&w=1200',
    metadata: { artist: 'Chris Marchese', collection: 'Wearable Art', status: 'Available' },
    price: 180,
    purchasable: true,
  },

  // ===== FILM STUDIO =====
  {
    id: 'film-1',
    zoneId: 'film_studio',
    title: 'The Martini Shot',
    subtitle: 'Feature Film (2023)',
    description: 'Associate Producer. Starring Matthew Modine and John Cleese. A compelling drama about the final days of a legendary director. Chris Marchese served as Associate Producer on this critically noted production.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1174206252?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { role: 'Associate Producer', cast: 'Matthew Modine, John Cleese', year: '2023', format: 'Feature Film' },
  },
  {
    id: 'film-2',
    zoneId: 'film_studio',
    title: 'This Mortal Coil',
    subtitle: 'Feature Film (2026)',
    description: 'Actor & Associate Producer. Filmed in Iceland. An epic existential journey exploring the boundaries between life and legacy. Chris Marchese stars and co-produces this ambitious international production.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1173874678?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { role: 'Actor & Associate Producer', location: 'Iceland', year: '2026', format: 'Feature Film' },
  },
  {
    id: 'film-3',
    zoneId: 'film_studio',
    title: 'Campaign Reel 2025',
    subtitle: 'Director\'s Cut',
    description: 'The complete campaign reel showcasing creative direction across fashion, automotive, and lifestyle projects. Produced by SET Marketing for global brand partners.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1173874041?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { type: 'Reel', duration: '3:42', format: '4K', production: 'SET Marketing' },
  },

  // ===== AUTOMOTIVE =====
  {
    id: 'auto-1',
    zoneId: 'automotive',
    title: 'BMW Partnership',
    subtitle: 'Brand Campaign',
    description: 'Exclusive editorial series produced for BMW through SET Marketing. Featuring blacked-out luxury vehicles shot against minimalist architectural backdrops in Toronto and Miami.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1173872281?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { client: 'BMW', project: 'Brand Campaign', year: '2025' },
  },
  {
    id: 'auto-2',
    zoneId: 'automotive',
    title: 'Track Day',
    subtitle: 'Event Coverage',
    description: 'Full documentation of an exclusive track day event, capturing the raw power and precision of elite performance vehicles. Content produced by SET Marketing.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1174206252?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { project: 'Event', location: 'Private Circuit', year: '2025' },
  },

  // ===== FASHION RUNWAY =====
  {
    id: 'fashion-1',
    zoneId: 'fashion_runway',
    title: 'Midnight Gold Jacket',
    subtitle: 'Outerwear Collection',
    description: 'Premium leather jacket with gold hardware accents. Tailored fit with signature lining.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop',
    metadata: { collection: 'FW25', material: 'Italian Leather' },
    price: 2800,
    purchasable: true,
  },
  {
    id: 'fashion-2',
    zoneId: 'fashion_runway',
    title: 'Essential Black Tee',
    subtitle: 'Core Collection',
    description: 'Heavyweight cotton tee with embossed logo detail. The foundation of every outfit.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop',
    metadata: { collection: 'Core', material: '300gsm Cotton' },
    price: 120,
    purchasable: true,
  },
  {
    id: 'fashion-3',
    zoneId: 'fashion_runway',
    title: 'Pace Setter Trousers',
    subtitle: 'Tailored Collection',
    description: 'Slim-cut tailored trousers with subtle gold stitching. Designed to move.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=800&auto=format&fit=crop',
    metadata: { collection: 'FW25', material: 'Wool Blend' },
    price: 680,
    purchasable: true,
  },

  // ===== CONTACT (Telephone Booth) =====
  {
    id: 'contact-1',
    zoneId: 'telephone_booth',
    title: 'Get In Touch',
    description: 'For collaborations, bookings, and inquiries. Canadian producer, actor, entrepreneur, and contemporary artist based in Toronto and Miami. University of Toronto alumnus.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=800&auto=format&fit=crop',
    metadata: {
      email: 'chris@marketingbyset.com',
      instagram: '@thechrismarchese',
      followers: '340K+',
      linkedin: 'Chris Marchese',
      location: 'Toronto / Miami',
    },
  },

  // ===== CHECKOUT (Money Pile) =====
  {
    id: 'checkout-1',
    zoneId: 'money_pile',
    title: 'Your Cart',
    description: 'Review your selections and proceed to checkout.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?q=80&w=800&auto=format&fit=crop',
    metadata: { note: 'Secure checkout powered by Stripe' },
  },

  // ===== CAPITAL ROOM =====
  // --- Capital Raise Advisory (Back wall) ---
  {
    id: 'cap-deals-1',
    zoneId: 'capital_deals',
    title: 'Capital Raise Advisory',
    subtitle: 'Raise Capital from a Position of Strength',
    description: 'Founders who succeed don\'t just present their business — they make it defensible by anticipating sharp questions and ensuring materials work cohesively. SET Enterprises provides a structured 4-stage process: Situational Review → Strategy & Scope → Build Materials → Go to Market. Book a consultation at chris@marketingbyset.com or via Calendly.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?q=80&w=800&auto=format&fit=crop',
    metadata: { founded: '2021', focus: 'Capital Raise Advisory', pipeline: '4-Stage Process', contact: 'chris@marketingbyset.com' },
  },
  // --- Advisory Packages (Left wall) ---
  {
    id: 'cap-svc-1',
    zoneId: 'capital_services',
    title: 'Digital Capital Launch',
    subtitle: '$12,500 — Advisory Package',
    description: 'AI-generated marketing assets, promotional visuals, and digital reels designed for capital raise positioning. Includes capital structuring guidance, investor introductions, and professional media production. Plus $2,000 investor origination fee.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=800&auto=format&fit=crop',
    metadata: { package: 'Digital Capital Launch', price: '$12,500', division: 'SET Capital Advisory' },
    price: 12500,
  },
  {
    id: 'cap-svc-2',
    zoneId: 'capital_services',
    title: 'Hybrid Media Capital Package',
    subtitle: '$15,000 — Advisory Package',
    description: 'Everything in Digital Capital Launch plus hybrid AI + real video production for pitch materials. Professional-grade investor decks, financial modeling review, and data room consultation. Includes $2,000 investor origination fee.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    metadata: { package: 'Hybrid Media Capital', price: '$15,000', division: 'SET Capital Advisory' },
    price: 15000,
  },
  {
    id: 'cap-svc-3',
    zoneId: 'capital_services',
    title: 'Premium Capital Activation',
    subtitle: '$20,000 — Advisory Package',
    description: 'The full capital raise experience: live event activation, movie-grade content production, investor origination, capital structuring, media production, and strategic advisory. Everything you need to raise capital from a position of strength. Includes $2,000 investor origination fee.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=800&auto=format&fit=crop',
    metadata: { package: 'Premium Capital Activation', price: '$20,000', division: 'SET Capital Advisory' },
    price: 20000,
  },
  // --- Commercial Bridge Lending (Right wall) ---
  {
    id: 'cap-bridge-1',
    zoneId: 'capital_clients',
    title: 'Commercial Bridge Lending',
    subtitle: 'SET Ventures — Bridge Loan Program',
    description: 'SET Ventures provides structured commercial bridge capital for acquisition, refinance, lease-up, repositioning, and value-add opportunities. $2MM–$25MM+ loan sizes, 9.50%–12.50% rates, 2–4 week closings. Designed for experienced sponsors seeking flexible structuring, interest-only terms, non-recourse options, and institutional underwriting.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?q=80&w=800&auto=format&fit=crop',
    metadata: {
      loanSize: '$2MM – $25MM+',
      rates: '9.50% – 12.50%',
      closing: '2–4 Weeks',
      maxLTV: '65%',
      maturity: 'Up to 2 Years',
      lienPosition: '1st Position',
      minimumFICO: '650',
      recourse: 'Typically Non-Recourse',
      markets: 'Nationwide Urban & Suburban',
    },
  },
  {
    id: 'cap-founders-1',
    zoneId: 'capital_clients',
    title: 'Founding Team',
    subtitle: 'SET Enterprises Leadership',
    description: 'Chris Marchese — Founder & Advisor. Canadian producer, actor, entrepreneur, and contemporary artist. Chris leads SET Enterprises\' capital advisory and strategic investment operations across Toronto and Miami.\n\nTyler Ferguson — Founder & Advisor. Co-leads SET Enterprises\' capital raise advisory practice, bringing institutional structuring expertise and investor network access to every engagement.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=800&auto=format&fit=crop',
    metadata: {
      chris: 'Founder & Advisor',
      tyler: 'Founder & Advisor',
      linkedin_chris: 'linkedin.com/in/thechrismarchese',
      linkedin_tyler: 'linkedin.com/in/tylerjamesferguson',
      contact: 'chris@marketingbyset.com',
    },
  },

  // ===== INFRASTRUCTURE ROOM =====
  {
    id: 'infra-proj-1',
    zoneId: 'infra_projects',
    title: 'Development',
    subtitle: 'Real Estate & Infrastructure',
    description: 'SET Enterprises identifies and develops real estate opportunities with a focus on mixed-use properties, commercial spaces, and residential developments in key markets including Toronto and Miami.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Development', markets: 'Toronto, Miami' },
  },
  {
    id: 'infra-proj-2',
    zoneId: 'infra_projects',
    title: 'Construction Management',
    subtitle: 'Project Delivery',
    description: 'End-to-end construction management services from pre-construction planning through final delivery. Our team coordinates architects, contractors, and trades to deliver projects on time and on budget.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Construction', type: 'Full-Cycle Management' },
  },
  {
    id: 'infra-proj-3',
    zoneId: 'infra_projects',
    title: 'Renovation & Repositioning',
    subtitle: 'Value-Add Projects',
    description: 'Strategic renovation and repositioning of underperforming assets. We transform properties to maximize market value through thoughtful design and efficient execution.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Renovation', strategy: 'Value-Add' },
  },
  {
    id: 'infra-proj-4',
    zoneId: 'infra_projects',
    title: 'Design & Architecture',
    subtitle: 'Creative Direction',
    description: 'Architectural design and creative direction for infrastructure projects. We blend aesthetic vision with functional requirements to create spaces that inspire.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Design', type: 'Architecture & Interiors' },
  },
  {
    id: 'infra-sys-1',
    zoneId: 'infra_systems',
    title: 'Systems & Technology',
    subtitle: 'Infrastructure Tech Stack',
    description: 'Proprietary technology systems that power SET Enterprises operations \u2014 from project management platforms to automated reporting and CRM integration. Our tech infrastructure enables scalability across all divisions.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Technology', type: 'Systems Integration' },
  },
  {
    id: 'infra-tech-1',
    zoneId: 'infra_tech',
    title: 'Blueprint & Planning',
    subtitle: 'Pre-Development',
    description: 'Comprehensive pre-development planning including feasibility studies, market analysis, zoning review, and architectural blueprinting. Every project begins with a detailed blueprint that maps the path from concept to completion.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Planning', phase: 'Pre-Development' },
  },

  // ===== GROWTH ROOM — marketingbyset.com =====
  {
    id: 'growth-svc-1',
    zoneId: 'growth_services',
    title: 'Revenue Architecture',
    subtitle: 'SET Marketing — Pillar 1',
    description: 'Strategic positioning and messaging refinement for brands seeking direction before execution. We partner with founders and leadership teams to refine positioning, clarify messaging, and identify high-leverage marketing opportunities. For companies generating $1M–$20M that want structured, measurable growth.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Revenue Architecture', division: 'SET Marketing', website: 'marketingbyset.com' },
  },
  {
    id: 'growth-svc-2',
    zoneId: 'growth_services',
    title: 'Performance & Acquisition',
    subtitle: 'SET Marketing — Pillar 2',
    description: 'Building and managing high-converting paid advertising campaigns. SET Marketing deploys $15M+ in ad spend across 12+ industries, driving predictable revenue through acquisition, automation, and conversion systems.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Performance & Acquisition', division: 'SET Marketing', adSpend: '$15M+' },
  },
  {
    id: 'growth-svc-3',
    zoneId: 'growth_services',
    title: 'On-Demand Growth Engine',
    subtitle: 'SET Marketing — Pillar 3',
    description: 'Executive-level marketing on demand. Structured growth, predictable revenue, and executive-level marketing for mid-market companies. SET Marketing builds the acquisition, automation, and conversion systems your business needs to scale.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Growth Engine', division: 'SET Marketing' },
  },
  {
    id: 'growth-svc-4',
    zoneId: 'growth_services',
    title: 'Fractional CMO & BPO',
    subtitle: 'SET Marketing',
    description: 'Executive-level marketing leadership on a fractional basis, plus Business Process Outsourcing solutions. Our team provides seasoned marketing leadership without the overhead of a full-time executive — driving strategy, team building, and revenue growth across 150+ companies scaled.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Fractional CMO & BPO', division: 'SET Marketing', companiesScaled: '150+' },
  },
  {
    id: 'growth-results-1',
    zoneId: 'growth_results',
    title: '$180M+ Revenue Generated',
    subtitle: 'Proven Results — marketingbyset.com',
    description: 'SET Marketing has generated over $180 million in revenue for clients. With $15M+ in ad spend deployed across 12+ industries and 150+ companies scaled, SET Marketing delivers structured growth and predictable revenue for companies generating $1M–$20M.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    metadata: { revenue: '$180M+', adSpend: '$15M+', industries: '12+', companiesScaled: '150+', website: 'marketingbyset.com' },
  },
  {
    id: 'growth-test-1',
    zoneId: 'growth_testimonials',
    title: 'Mahmoud Elminawi',
    subtitle: 'Client Testimonial',
    description: '\"SET Marketing transformed our digital presence and drove measurable results from day one. Chris and his team understand the intersection of brand and performance in a way that few agencies do. Their strategic approach delivered ROI that exceeded our expectations.\"',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=800&auto=format&fit=crop',
    metadata: { client: 'Mahmoud Elminawi', type: 'Testimonial' },
  },
  {
    id: 'growth-test-2',
    zoneId: 'growth_testimonials',
    title: 'Sean Huley',
    subtitle: 'Client Testimonial',
    description: '\"Working with SET Marketing was a game-changer for our business. The fractional CMO model gave us executive-level marketing leadership at a fraction of the cost. They don\'t just run campaigns \u2014 they build sustainable growth engines.\"',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop',
    metadata: { client: 'Sean Huley', type: 'Testimonial' },
  },
  {
    id: 'growth-test-3',
    zoneId: 'growth_testimonials',
    title: 'George Pintilie',
    subtitle: 'Client Testimonial',
    description: '\"Chris Marchese and the SET team brought a level of sophistication and creativity to our brand that we hadn\'t seen from other agencies. Their understanding of luxury positioning and performance marketing is unmatched.\"',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop',
    metadata: { client: 'George Pintilie', type: 'Testimonial' },
  },
  {
    id: 'growth-social-1',
    zoneId: 'growth_social',
    title: '@thechrismarchese',
    subtitle: '340K+ Followers',
    description: 'Chris Marchese\'s social media presence spans 340K+ followers across platforms. Content covers entrepreneurship, luxury lifestyle, business insights, and behind-the-scenes of SET Enterprises operations. Follow @thechrismarchese for daily content.',
    mediaType: 'embed',
    mediaUrl: 'https://www.instagram.com/p/CoMh7AivwUq/embed',
    metadata: { handle: '@thechrismarchese', followers: '340K+', platform: 'Instagram' },
  },
  {
    id: 'growth-sales-1',
    zoneId: 'growth_social',
    title: 'SET Sales Consulting & Academy',
    subtitle: '2-3x ROI Guaranteed',
    description: 'SET Sales Consulting & Academy (est. 2020) provides sales training, process optimization, and consulting that delivers 2-3x return on investment. Our proven methodology transforms sales teams through structured training programs, CRM optimization, and performance coaching.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32b7?q=80&w=800&auto=format&fit=crop',
    metadata: { division: 'SET Sales Consulting & Academy', founded: '2020', roi: '2-3x', type: 'Training & Consulting' },
  },
]

export function getContentByZone(zoneId: string): ContentItem[] {
  return SAMPLE_CONTENT.filter((item) => item.zoneId === zoneId)
}

export function getContentById(id: string): ContentItem | undefined {
  return SAMPLE_CONTENT.find((item) => item.id === id)
}
