import type { ContentItem } from '@/types'

export const SAMPLE_CONTENT: ContentItem[] = [
  // ===== ART GALLERY =====
  {
    id: 'art-1',
    zoneId: 'art_gallery',
    title: 'Golden Hour',
    subtitle: 'Oil on Canvas \u2014 Art by Marchese',
    description: 'A study in light and shadow capturing the essence of the golden hour across an urban landscape. Part of the Art by Marchese collection, exhibited at Art Basel Miami and galleries in Toronto, Miami, and NYC. Available on Artsy.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=800&auto=format&fit=crop',
    metadata: { artist: 'Chris Marchese', medium: 'Oil on Canvas', year: '2024', size: '48\" x 36\"', gallery: 'Art Basel Miami' },
    price: 12000,
    purchasable: true,
  },
  {
    id: 'art-2',
    zoneId: 'art_gallery',
    title: 'Concrete Dreams',
    subtitle: 'Mixed Media \u2014 Pop-Culture Series',
    description: 'An exploration of urban architecture through mixed media, blending photography with painted elements. Chris Marchese\'s pop-culture art has been featured in galleries across Toronto, Miami, and New York City since 2015.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?q=80&w=800&auto=format&fit=crop',
    metadata: { artist: 'Chris Marchese', medium: 'Mixed Media', year: '2024', size: '36\" x 24\"', collection: 'Pop-Culture Series' },
    price: 8500,
    purchasable: true,
  },
  {
    id: 'art-3',
    zoneId: 'art_gallery',
    title: 'The Observer',
    subtitle: 'Acrylic on Panel',
    description: 'A bold portrait piece exploring themes of perception and identity in the modern digital age. Art by Marchese \u2014 established 2015, shown at Art Basel and available on Artsy.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?q=80&w=800&auto=format&fit=crop',
    metadata: { artist: 'Chris Marchese', medium: 'Acrylic on Panel', year: '2025', size: '40\" x 30\"', platform: 'Artsy' },
    price: 15000,
    purchasable: true,
  },
  {
    id: 'art-4',
    zoneId: 'art_gallery',
    title: 'Velocity',
    subtitle: 'Digital Print \u2014 Automotive Series',
    description: 'A high-contrast composition inspired by automotive culture and the beauty of speed, rendered in stark black and gold. Part of the Art by Marchese automotive series.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=800&auto=format&fit=crop',
    metadata: { artist: 'Chris Marchese', medium: 'Digital Print', year: '2025', size: '60\" x 40\"' },
    price: 5000,
    purchasable: true,
  },
  {
    id: 'art-5',
    zoneId: 'art_gallery',
    title: 'Set The Pace',
    subtitle: 'Photography',
    description: 'A defining image from the Setting The Pace series \u2014 movement, intention, and vision captured in a single frame. Art by Marchese, est. 2015.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1551000697-310e5bd7dc05?q=80&w=800&auto=format&fit=crop',
    metadata: { artist: 'Chris Marchese', medium: 'Photography', year: '2025', size: '30\" x 20\"' },
    price: 3500,
    purchasable: true,
  },

  // ===== FILM STUDIO =====
  {
    id: 'film-1',
    zoneId: 'film_studio',
    title: 'The Martini Shot',
    subtitle: 'Feature Film (2023)',
    description: 'Associate Producer. Starring Matthew Modine and John Cleese. A compelling drama about the final days of a legendary director. Chris Marchese served as Associate Producer on this critically noted production.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1174206252?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { role: 'Associate Producer', cast: 'Matthew Modine, John Cleese', year: '2023', format: 'Feature Film' },
  },
  {
    id: 'film-2',
    zoneId: 'film_studio',
    title: 'This Mortal Coil',
    subtitle: 'Feature Film (2026)',
    description: 'Actor & Associate Producer. Filmed in Iceland. An epic existential journey exploring the boundaries between life and legacy. Chris Marchese stars and co-produces this ambitious international production.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1173874678?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { role: 'Actor & Associate Producer', location: 'Iceland', year: '2026', format: 'Feature Film' },
  },
  {
    id: 'film-3',
    zoneId: 'film_studio',
    title: 'Campaign Reel 2025',
    subtitle: 'Director\'s Cut',
    description: 'The complete campaign reel showcasing creative direction across fashion, automotive, and lifestyle projects. Produced by SET Marketing for global brand partners.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1173874041?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { type: 'Reel', duration: '3:42', format: '4K', production: 'SET Marketing' },
  },

  // ===== AUTOMOTIVE =====
  {
    id: 'auto-1',
    zoneId: 'automotive',
    title: 'BMW Partnership',
    subtitle: 'Brand Campaign',
    description: 'Exclusive editorial series produced for BMW through SET Marketing. Featuring blacked-out luxury vehicles shot against minimalist architectural backdrops in Toronto and Miami.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1173872281?autoplay=1&loop=1&autopause=0&muted=1',
    metadata: { client: 'BMW', project: 'Brand Campaign', year: '2025' },
  },
  {
    id: 'auto-2',
    zoneId: 'automotive',
    title: 'Track Day',
    subtitle: 'Event Coverage',
    description: 'Full documentation of an exclusive track day event, capturing the raw power and precision of elite performance vehicles. Content produced by SET Marketing.',
    mediaType: 'embed',
    mediaUrl: 'https://player.vimeo.com/video/1174206252?autoplay=1&loop=1&autopause=0&muted=1', // Reusing vimeo link as placeholder
    metadata: { project: 'Event', location: 'Private Circuit', year: '2025' },
  },

  // ===== FASHION RUNWAY =====
  {
    id: 'fashion-1',
    zoneId: 'fashion_runway',
    title: 'Midnight Gold Jacket',
    subtitle: 'Outerwear Collection',
    description: 'Premium leather jacket with gold hardware accents. Tailored fit with signature lining.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop',
    metadata: { collection: 'FW25', material: 'Italian Leather' },
    price: 2800,
    purchasable: true,
  },
  {
    id: 'fashion-2',
    zoneId: 'fashion_runway',
    title: 'Essential Black Tee',
    subtitle: 'Core Collection',
    description: 'Heavyweight cotton tee with embossed logo detail. The foundation of every outfit.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=800&auto=format&fit=crop',
    metadata: { collection: 'Core', material: '300gsm Cotton' },
    price: 120,
    purchasable: true,
  },
  {
    id: 'fashion-3',
    zoneId: 'fashion_runway',
    title: 'Pace Setter Trousers',
    subtitle: 'Tailored Collection',
    description: 'Slim-cut tailored trousers with subtle gold stitching. Designed to move.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=800&auto=format&fit=crop',
    metadata: { collection: 'FW25', material: 'Wool Blend' },
    price: 680,
    purchasable: true,
  },

  // ===== CONTACT (Telephone Booth) =====
  {
    id: 'contact-1',
    zoneId: 'telephone_booth',
    title: 'Get In Touch',
    description: 'For collaborations, bookings, and inquiries. Canadian producer, actor, entrepreneur, and contemporary artist based in Toronto and Miami. University of Toronto alumnus.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=800&auto=format&fit=crop',
    metadata: {
      email: 'chris@marketingbyset.com',
      instagram: '@thechrismarchese',
      followers: '340K+',
      linkedin: 'Chris Marchese',
      location: 'Toronto / Miami',
    },
  },

  // ===== CHECKOUT (Money Pile) =====
  {
    id: 'checkout-1',
    zoneId: 'money_pile',
    title: 'Your Cart',
    description: 'Review your selections and proceed to checkout.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?q=80&w=800&auto=format&fit=crop',
    metadata: { note: 'Secure checkout powered by Stripe' },
  },

  // ===== CAPITAL ROOM =====
  {
    id: 'cap-deals-1',
    zoneId: 'capital_deals',
    title: 'Deal Origination',
    subtitle: 'SET Ventures Pipeline',
    description: 'SET Ventures (est. 2021) sources, evaluates, and closes private equity and strategic investment opportunities. Our disciplined pipeline moves from Sourcing \u2192 Evaluation \u2192 Due Diligence \u2192 Closing, ensuring every deal meets our rigorous standards.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?q=80&w=800&auto=format&fit=crop',
    metadata: { founded: '2021', focus: 'Private Equity & Funding', pipeline: '4-Stage Process' },
  },
  {
    id: 'cap-svc-1',
    zoneId: 'capital_services',
    title: 'Investment Advisory',
    subtitle: 'SET Ventures',
    description: 'Comprehensive investment advisory services for high-net-worth individuals and institutional partners. We provide strategic guidance on portfolio allocation, deal structuring, and risk management across diverse asset classes.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Investment Advisory', division: 'SET Ventures' },
  },
  {
    id: 'cap-svc-2',
    zoneId: 'capital_services',
    title: 'Private Equity',
    subtitle: 'SET Ventures',
    description: 'Direct private equity investments in high-growth companies. SET Ventures identifies undervalued opportunities and works hands-on with management teams to accelerate value creation.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Private Equity', division: 'SET Ventures' },
  },
  {
    id: 'cap-svc-3',
    zoneId: 'capital_services',
    title: 'Strategic Capital',
    subtitle: 'SET Ventures',
    description: 'Strategic capital deployment for businesses at inflection points. We provide growth capital paired with operational expertise from the SET Enterprises ecosystem to accelerate scaling.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Strategic Capital', division: 'SET Ventures' },
  },
  {
    id: 'cap-clients-1',
    zoneId: 'capital_clients',
    title: 'Portfolio Companies',
    subtitle: 'SET Ventures Portfolio',
    description: 'SET Ventures maintains an active portfolio of companies across technology, real estate, consumer brands, and services. Each portfolio company benefits from the full SET Enterprises ecosystem including marketing, infrastructure, and operational support.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=800&auto=format&fit=crop',
    metadata: { division: 'SET Ventures', type: 'Portfolio Overview' },
  },

  // ===== INFRASTRUCTURE ROOM =====
  {
    id: 'infra-proj-1',
    zoneId: 'infra_projects',
    title: 'Development',
    subtitle: 'Real Estate & Infrastructure',
    description: 'SET Enterprises identifies and develops real estate opportunities with a focus on mixed-use properties, commercial spaces, and residential developments in key markets including Toronto and Miami.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Development', markets: 'Toronto, Miami' },
  },
  {
    id: 'infra-proj-2',
    zoneId: 'infra_projects',
    title: 'Construction Management',
    subtitle: 'Project Delivery',
    description: 'End-to-end construction management services from pre-construction planning through final delivery. Our team coordinates architects, contractors, and trades to deliver projects on time and on budget.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Construction', type: 'Full-Cycle Management' },
  },
  {
    id: 'infra-proj-3',
    zoneId: 'infra_projects',
    title: 'Renovation & Repositioning',
    subtitle: 'Value-Add Projects',
    description: 'Strategic renovation and repositioning of underperforming assets. We transform properties to maximize market value through thoughtful design and efficient execution.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Renovation', strategy: 'Value-Add' },
  },
  {
    id: 'infra-proj-4',
    zoneId: 'infra_projects',
    title: 'Design & Architecture',
    subtitle: 'Creative Direction',
    description: 'Architectural design and creative direction for infrastructure projects. We blend aesthetic vision with functional requirements to create spaces that inspire.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Design', type: 'Architecture & Interiors' },
  },
  {
    id: 'infra-sys-1',
    zoneId: 'infra_systems',
    title: 'Systems & Technology',
    subtitle: 'Infrastructure Tech Stack',
    description: 'Proprietary technology systems that power SET Enterprises operations \u2014 from project management platforms to automated reporting and CRM integration. Our tech infrastructure enables scalability across all divisions.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Technology', type: 'Systems Integration' },
  },
  {
    id: 'infra-tech-1',
    zoneId: 'infra_tech',
    title: 'Blueprint & Planning',
    subtitle: 'Pre-Development',
    description: 'Comprehensive pre-development planning including feasibility studies, market analysis, zoning review, and architectural blueprinting. Every project begins with a detailed blueprint that maps the path from concept to completion.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Planning', phase: 'Pre-Development' },
  },

  // ===== GROWTH ROOM =====
  {
    id: 'growth-svc-1',
    zoneId: 'growth_services',
    title: 'Strategic Advisory',
    subtitle: 'SET Marketing',
    description: 'High-level strategic advisory for brands looking to scale. SET Marketing (est. 2019) has generated over $500M+ in client revenue through data-driven strategy, creative execution, and performance marketing. Clients include BMW, Wynn Resorts, and Huawei.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Strategic Advisory', division: 'SET Marketing', founded: '2019' },
  },
  {
    id: 'growth-svc-2',
    zoneId: 'growth_services',
    title: 'Fractional CMO',
    subtitle: 'SET Marketing',
    description: 'Executive-level marketing leadership on a fractional basis. Our Fractional CMO service provides companies with seasoned marketing leadership without the overhead of a full-time executive, driving strategy, team building, and revenue growth.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Fractional CMO', division: 'SET Marketing' },
  },
  {
    id: 'growth-svc-3',
    zoneId: 'growth_services',
    title: 'Creative & Brand Development',
    subtitle: 'SET Marketing',
    description: 'Full-service creative and brand development from identity design to campaign execution. We build brands that resonate \u2014 from visual identity and messaging to multi-channel creative campaigns that drive measurable results.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'Creative & Brand Dev', division: 'SET Marketing' },
  },
  {
    id: 'growth-svc-4',
    zoneId: 'growth_services',
    title: 'BPO Solutions',
    subtitle: 'SET Marketing',
    description: 'Business Process Outsourcing solutions that enable companies to scale operations efficiently. Our BPO services cover marketing operations, customer acquisition, sales support, and back-office functions with guaranteed performance metrics.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop',
    metadata: { service: 'BPO Solutions', division: 'SET Marketing' },
  },
  {
    id: 'growth-results-1',
    zoneId: 'growth_results',
    title: '$500M+ Client Revenue',
    subtitle: 'Proven Results',
    description: 'SET Marketing has generated over $500 million in revenue for clients since 2019. Our performance marketing methodology has achieved a 27% average reduction in cost-per-acquisition across campaigns for brands including BMW, Wynn Resorts, Huawei, and dozens of growth-stage companies.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    metadata: { revenue: '$500M+', cpaReduction: '27%', clients: 'BMW, Wynn, Huawei', rating: '5.0 Stars (29 Reviews)' },
  },
  {
    id: 'growth-test-1',
    zoneId: 'growth_testimonials',
    title: 'Mahmoud Elminawi',
    subtitle: 'Client Testimonial',
    description: '"SET Marketing transformed our digital presence and drove measurable results from day one. Chris and his team understand the intersection of brand and performance in a way that few agencies do. Their strategic approach delivered ROI that exceeded our expectations."',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=800&auto=format&fit=crop',
    metadata: { client: 'Mahmoud Elminawi', type: 'Testimonial' },
  },
  {
    id: 'growth-test-2',
    zoneId: 'growth_testimonials',
    title: 'Sean Huley',
    subtitle: 'Client Testimonial',
    description: '"Working with SET Marketing was a game-changer for our business. The fractional CMO model gave us executive-level marketing leadership at a fraction of the cost. They don\'t just run campaigns \u2014 they build sustainable growth engines."',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop',
    metadata: { client: 'Sean Huley', type: 'Testimonial' },
  },
  {
    id: 'growth-test-3',
    zoneId: 'growth_testimonials',
    title: 'George Pintilie',
    subtitle: 'Client Testimonial',
    description: '"Chris Marchese and the SET team brought a level of sophistication and creativity to our brand that we hadn\'t seen from other agencies. Their understanding of luxury positioning and performance marketing is unmatched."',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop',
    metadata: { client: 'George Pintilie', type: 'Testimonial' },
  },
  {
    id: 'growth-social-1',
    zoneId: 'growth_social',
    title: '@thechrismarchese',
    subtitle: '340K+ Followers',
    description: 'Chris Marchese\'s social media presence spans 340K+ followers across platforms. Content covers entrepreneurship, luxury lifestyle, business insights, and behind-the-scenes of SET Enterprises operations. Follow @thechrismarchese for daily content.',
    mediaType: 'embed',
    mediaUrl: 'https://www.instagram.com/p/CoMh7AivwUq/embed', // Placeholder instagram embed for visual representation
    metadata: { handle: '@thechrismarchese', followers: '340K+', platform: 'Instagram' },
  },
  {
    id: 'growth-sales-1',
    zoneId: 'growth_social',
    title: 'SET Sales Consulting & Academy',
    subtitle: '2-3x ROI Guaranteed',
    description: 'SET Sales Consulting & Academy (est. 2020) provides sales training, process optimization, and consulting that delivers 2-3x return on investment. Our proven methodology transforms sales teams through structured training programs, CRM optimization, and performance coaching.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32b7?q=80&w=800&auto=format&fit=crop',
    metadata: { division: 'SET Sales Consulting & Academy', founded: '2020', roi: '2-3x', type: 'Training & Consulting' },
  },
]

export function getContentByZone(zoneId: string): ContentItem[] {
  return SAMPLE_CONTENT.filter((item) => item.zoneId === zoneId)
}

export function getContentById(id: string): ContentItem | undefined {
  return SAMPLE_CONTENT.find((item) => item.id === id)
}
